'use client';
import { MessageCircle, Paperclip } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { ARTIST } from '@/lib/data';
import { trackWhatsAppClick } from '@/lib/analytics';
const places=['Braço','Costelas','Costas','Perna','Colo']; const sizes=['Pequena','Média','Grande','Fechamento'];
export default function QuoteForm(){ const [place,setPlace]=useState(places[0]); const [size,setSize]=useState(sizes[1]);
  function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); const fd=new FormData(e.currentTarget); trackWhatsAppClick({source:'quote_form'}); const msg=`Olá, DW. Quero um orçamento.\nNome: ${fd.get('nome')}\nWhatsApp: ${fd.get('whatsapp')}\nLocal: ${place}\nTamanho: ${size}\nDescrição: ${fd.get('descricao')}\nTenho referências para enviar na conversa.`; window.open(`https://wa.me/${ARTIST.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank'); }
  return <section id="orcamento" className="bg-paper-950 px-5 py-24 text-paper-100 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="label-section text-paper-400">09 — Orçamento</p><h2 className="mt-6 font-serif text-5xl font-light lg:text-7xl">Conte a marca que você quer carregar.</h2><p className="mt-6 max-w-xl text-paper-300">Quanto mais contexto, mais precisa será a proposta. O envio do arquivo serve apenas como referência inicial; nenhuma imagem é enviada ao site.</p><a onClick={()=>trackWhatsAppClick({source:'direct_link'})} className="btn-outline mt-8 border-paper-100 text-paper-100 hover:bg-paper-100 hover:text-ink" href={`https://wa.me/${ARTIST.whatsapp}`}><MessageCircle size={16}/> WhatsApp direto</a></div><form onSubmit={submit} className="grid gap-5"><input name="nome" required placeholder="Nome" className="border border-paper-100/20 bg-transparent p-4 outline-none placeholder:text-paper-400"/><input name="whatsapp" required placeholder="WhatsApp" className="border border-paper-100/20 bg-transparent p-4 outline-none placeholder:text-paper-400"/><textarea name="descricao" required rows={5} placeholder="Descrição da ideia" className="border border-paper-100/20 bg-transparent p-4 outline-none placeholder:text-paper-400"/><Chip label="Local do corpo" items={places} value={place} setValue={setPlace}/><Chip label="Tamanho" items={sizes} value={size} setValue={setSize}/><label className="flex items-center gap-3 border border-paper-100/20 p-4 text-paper-300"><Paperclip size={16}/>Referência visual<input type="file" className="hidden" accept="image/*"/></label><button className="btn-primary bg-paper-100 text-ink hover:bg-gold-pale" type="submit">Enviar para orçamento</button></form></div></section> }
function Chip({label,items,value,setValue}:{label:string;items:string[];value:string;setValue:(v:string)=>void}){ return <div><p className="mb-3 text-[10px] uppercase tracking-[0.3em] text-paper-400">{label}</p><div className="flex flex-wrap gap-2">{items.map(i=><button type="button" onClick={()=>setValue(i)} className={`border px-4 py-2 text-xs uppercase tracking-[0.2em] ${value===i?'border-gold-pale bg-gold-pale text-ink':'border-paper-100/20 text-paper-300'}`} key={i}>{i}</button>)}</div></div> }
