'use client';
import { useEffect, useRef, useState } from 'react';
import { Download, RotateCcw, Upload } from 'lucide-react';
import { flashItems } from '@/lib/data';

type KonvaType = typeof import('konva');
export default function SimuladorKonva(){ return <section id="simulador" className="bg-paper-100 px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto max-w-7xl"><p className="label-section">04 — Simulador virtual</p><h2 className="mt-6 max-w-3xl font-serif text-5xl font-light lg:text-7xl">Teste o flash antes da pele.</h2><p className="mt-5 max-w-2xl text-ink-muted">Envie uma foto do corpo ou use a amostra. Arraste, gire e redimensione a tatuagem. Tudo acontece localmente no seu navegador.</p><Simulator /></div></section> }
function Simulator(){
  const host = useRef<HTMLDivElement>(null); const stageRef = useRef<any>(null); const layerRef = useRef<any>(null); const tattooRef = useRef<any>(null); const transformerRef = useRef<any>(null); const konvaRef = useRef<KonvaType | null>(null);
  const [selected,setSelected]=useState(flashItems[0].name); const [ready,setReady]=useState(false);
  useEffect(()=>{ const fromUrl = new URLSearchParams(window.location.hash.split('?')[1] ?? window.location.search).get('flash'); if(fromUrl && flashItems.some(f=>f.name===fromUrl)) setSelected(fromUrl); },[]);
  useEffect(()=>{ let alive=true; import('konva').then((Konva)=>{ if(!alive || !host.current) return; konvaRef.current=Konva; const width=Math.min(host.current.clientWidth,900); const height=560; const stage=new Konva.default.Stage({container:host.current,width,height}); const layer=new Konva.default.Layer(); stage.add(layer); stageRef.current=stage; layerRef.current=layer; drawSample(Konva,layer,width,height); const transformer=new Konva.default.Transformer({borderStroke:'#d4b896',anchorStroke:'#0f0c08',anchorFill:'#d4b896'}); transformerRef.current=transformer; layer.add(transformer); setReady(true); }); return()=>{alive=false; stageRef.current?.destroy();}; },[]);
  useEffect(()=>{ if(ready) addTattoo(selected); },[selected,ready]);
  function drawSample(Konva:KonvaType, layer:any, width:number, height:number){ layer.destroyChildren(); const bg=new Konva.default.Rect({x:0,y:0,width,height,fill:'#e0d9c8'}); const body=new Konva.default.Rect({x:width*.32,y:50,width:width*.36,height:460,cornerRadius:180,fill:'#c8a98f',stroke:'#6b5f50',strokeWidth:1}); const label=new Konva.default.Text({x:20,y:20,text:'amostra local',fontSize:12,fontFamily:'Manrope',fill:'#6b5f50'}); layer.add(bg,body,label); }
  function addTattoo(name:string){ const Konva=konvaRef.current; const layer=layerRef.current; const stage=stageRef.current; if(!Konva||!layer||!stage) return; tattooRef.current?.destroy(); const item=flashItems.find(f=>f.name===name)??flashItems[0]; Konva.default.Image.fromURL(item.simSrc,(img:any)=>{ img.setAttrs({x:stage.width()/2-80,y:210,width:160,height:160,draggable:true,opacity:.86}); tattooRef.current=img; layer.add(img); transformerRef.current.nodes([img]); img.moveToTop(); transformerRef.current.moveToTop(); layer.draw(); }); }
  function upload(file?:File){ if(!file || !konvaRef.current || !layerRef.current || !stageRef.current) return; const url=URL.createObjectURL(file); const stage=stageRef.current; const layer=layerRef.current; const Konva=konvaRef.current; Konva.default.Image.fromURL(url,(img:any)=>{ layer.destroyChildren(); const scale=Math.max(stage.width()/img.width(), stage.height()/img.height()); img.setAttrs({x:(stage.width()-img.width()*scale)/2,y:(stage.height()-img.height()*scale)/2,scaleX:scale,scaleY:scale}); layer.add(img); const transformer=new Konva.default.Transformer({borderStroke:'#d4b896',anchorStroke:'#0f0c08',anchorFill:'#d4b896'}); transformerRef.current=transformer; layer.add(transformer); addTattoo(selected); URL.revokeObjectURL(url); }); }
  return <div className="mt-12 grid gap-8 lg:grid-cols-[320px_1fr]"><aside className="space-y-4 border border-ink/15 p-5"><label className="btn-outline w-full gap-3"><Upload size={16}/>Enviar foto<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label><button className="btn-outline w-full gap-3" onClick={()=>{ const k=konvaRef.current,l=layerRef.current,s=stageRef.current; if(k&&l&&s){drawSample(k,l,s.width(),s.height()); addTattoo(selected);} }}><RotateCcw size={16}/>Usar amostra</button><select className="w-full border border-ink/20 bg-paper-50 p-4" value={selected} onChange={e=>setSelected(e.target.value)}>{flashItems.map(f=><option key={f.id}>{f.name}</option>)}</select><button className="btn-primary w-full gap-3" onClick={()=>{ const url=stageRef.current?.toDataURL({pixelRatio:2}); if(url){ const a=document.createElement('a'); a.href=url; a.download='simulador-dw-tattooer.png'; a.click(); } }}><Download size={16}/>Baixar prévia</button><p className="text-xs leading-relaxed text-ink-muted">Toque na arte para revelar os controles. Arraste os cantos para escalar e a alça para girar.</p></aside><div className="overflow-hidden border border-ink/15 bg-paper-200"><div ref={host} className="min-h-[560px] w-full" /></div></div>;
}
